### ISSUE TITLE
SCSS编译不成功。这样我没有办法在修改SCSS后，查看页面样式变化。 我应该怎办呢？

### ISSUE THREAD

**Issue by eddieeddieeddiejones** [o2team/Mail-Signature-Generator#1]
在项目中找不到这三个文件。
@import 'function';
@import 'mod_border';
@import 'web_font_icon';
SCSS编译不成功。
这样我没有办法在修改SCSS后，查看页面样式变化。
我应该怎办呢？

**Comment by Tingglelaoo** [comment]
@eddieeddieeddiejones  谢谢你的反馈。因为忽略文件中添加了*.scss，所以把引入文件忘记提交了。现在已经补充上，你update一下。如还有其它问题，欢迎你继续反馈，感谢。
